### PR TITLE
adding contextual logging

### PR DESCRIPTION
**Pull request by nitishchauhan0022**
Adding contextual logging in registration component
Reference: #https://github.com/open-cluster-management-io/ocm/issues/191

For More Info:
https://www.kubernetes.dev/blog/2022/05/25/contextual-logging/
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

### CODE REVIEW

**Comment by qiujian16** [comment]
thanks for your work, since we've moved the code to ocm repo already, https://github.com/open-cluster-management-io/registration#note-do-not-edit-any-file-in-this-repo. would you create a PR in ocm repo instead?

**Comment by nitishchauhan0022** [comment]
ok

**Comment by nitishchauhan0022** [comment]
hey @xuezhaojun this pr need to be opened to the main ocm repo, and since that contains other components as well, so i will open a combined pr with 1-2 days for all components in that repo. Hope, you understand have not been geeting time to work on it.

**Comment by xuezhaojun** [comment]
> hey @xuezhaojun this pr need to be opened to the main ocm repo, and since that contains other components as well, so i will open a combined pr with 1-2 days for all components in that repo. Hope, you understand have not been geeting time to work on it.

Got it！Thanks！

**Pull request closed without merging**
