### PR TITLE
cherry-pick: increase qps and burst

### PR DESCRIPTION
**Pull request by skeeey**

### CODE REVIEW

**Comment by smithbw88** [comment]
@skeeey @qiujian16 @blkingrh , Is this change set approved for 2.1.2?

The only changes that should be merged to the 2.1.x stream at this time are reversioning changes (which should be complete) and changes explicitly related to the upgrade emergency fix.

If this is not one of the above, could you please revert it and wait until the 2.1.3 cycle in January to deliver it?  Thanks!

**Comment by blkingrh** [comment]
This is unrelated to the Install work on the upgrade issue, so it should wait for 2.1.3.

**Comment by qiujian16** [comment]
ah, ok this relates to a performance issue @TheRealHaoLiu raises. @skeeey Let's revert it. @smithbw88 sorry for that

**Comment by skeeey** [comment]
revert on this pr https://github.com/open-cluster-management/registration/pull/102

**Pull request merged**
