### PR TITLE
use registration feature gates constants & variabels which in api repo

### PR DESCRIPTION
**Pull request by ivan-cai**
Signed-off-by: ivan-cai <caijing.cai@alibaba-inc.com>

In [api repo pr 162](https://github.com/open-cluster-management-io/api/pull/162), we move feature gates from registration repo to api repo, this pr is changed to use constants & variables in api repo

### CODE REVIEW

**Comment by ivan-cai** [comment]
@qiujian16 Plz review. Thanks!

**Comment by qiujian16** [comment]
I think you would need to run `make update`?

/approve

**Comment by ivan-cai** [comment]
> I think you would need to run `make update`?
> 
> /approve

@qiujian16 Thx, plz review. I have run `make update` and re-commit.

**Pull request merged**
