### PR TITLE
Change KUSTOMIZE related path to absolute path

### PR DESCRIPTION
**Pull request by xuezhaojun**
Signed-off-by: xuezhao <zxue@redhat.com>

### CODE REVIEW

**Comment by qiujian16** [comment]
why it must be absolute path?

**Comment by skeeey** [comment]
If user already has kustomize in their env, and use KUSTOMIZE to set their kustomize, the make will be failed

**Comment by xuezhaojun** [comment]
> why it must be absolute path?

In our makefile, we also provide users an option to use an existing kustomize, and build will failed if we use related path.
```mk
ensure-kustomize:
ifeq "" "$(wildcard $(KUSTOMIZE))"
	$(info Installing kustomize into '$(KUSTOMIZE)')
	mkdir -p '$(kustomize_dir)'
	curl -s -f -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F$(KUSTOMIZE_VERSION)/$(KUSTOMIZE_ARCHIVE_NAME) -o '$(kustomize_dir)$(KUSTOMIZE_ARCHIVE_NAME)'
	tar -C '$(kustomize_dir)' -zvxf '$(kustomize_dir)$(KUSTOMIZE_ARCHIVE_NAME)'
	chmod +x '$(KUSTOMIZE)';
else
	$(info Using existing kustomize from "$(KUSTOMIZE)"). #  Option to use an existing kustomize
endif
```

**Comment by qiujian16** [comment]
if a user has a kustomize binary in `/usr/local/bin`. How does this fix help?

**Comment by skeeey** [comment]
```
KUSTOMIZE?=$(PERMANENT_TMP_GOPATH)/bin/kustomize
```
if user does not define the `KUSTOMIZE`, the `$(PERMANENT_TMP_GOPATH)/bin/kustomize` will be used, even the kustomize is in the  user `PATH`, so current implement is that if user want to use his own kustomize, he must specify the `KUSTOMIZE`

**Comment by qiujian16** [comment]
I see. I think we need to fix it in other repos also.

/approve
/lgtm

**Comment by xuezhaojun** [comment]
> I see. I think we need to fix it in other repos also.
> 
> /approve
> /lgtm

Yes, I am working on repo work and addon-framework about the same issue.

**Pull request merged**
