### PR TITLE
upgrade CRD to v1 and k8s lib to v0.21.0-rc.0

### PR DESCRIPTION
**Pull request by zhiweiyin318**
1. ~upgrade webhook to v1~ (openshift/generic-admission-server does not support webhook v1 yet)
2. upgrade CRD to v1 in deploy
3. upgrade k8s lib to v0.21.0-rc.0
4. upgrade kubebuilder to v1.19.2

### CODE REVIEW

**Comment by qiujian16** [comment]
also need to change here https://github.com/open-cluster-management/registration/blob/main/test/e2e/loopback_test.go#L46

**Comment by zhiweiyin318** [comment]
> also need to change here https://github.com/open-cluster-management/registration/blob/main/test/e2e/loopback_test.go#L46

have changed to v1

**Review by qiujian16 — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
